load("//buck_imports:loom_path.bzl", "loom_path")

cxx_binary(
    name = "stress_test",
    srcs = [
        "stress_test.cpp",
    ],
    compiler_flags = [
        "-fvisibility=hidden",
        "-fexceptions",
        "-fPIE",
        "-DLOG_TAG=\"yarn\"",
        "-g",
    ],
    linker_flags = [
        "-pie",
        "-g",
    ],
    deps = [
        loom_path("cpp/yarn:yarn"),
    ],
)
