load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_cxx_binary", "profilo_path")

profilo_cxx_binary(
    name = "stress_test",
    srcs = [
        "stress_test.cpp",
    ],
    compiler_flags = [
        "-fvisibility=hidden",
        "-fexceptions",
        "-fPIE",
        "-DLOG_TAG=\"yarn\"",
        "-g",
    ],
    linker_flags = [
        "-pie",
        "-g",
    ],
    deps = [
        profilo_path("cpp/yarn:yarn"),
    ],
)
