load("//buck_imports:loom_path.bzl", "loom_path")
load("//tools/build_defs:robolectric3_test.bzl", "robolectric3_test")

android_library(
    name = "utils",
    srcs = glob(
        ["*.java"],
        excludes = ["*Test.java"],
    ),
    visibility = [
        loom_path("java/test/com/facebook/loom/core:core"),
    ],
    deps = [
        "//java/com/facebook/testing/powermock:powermock",
        loom_path("deps/jsr-305:jsr-305"),
        loom_path("deps/proguard:annotations"),
        loom_path("java/main/com/facebook/loom/logger:logger"),
        "//third-party/java/junit:junit",
    ],
)

robolectric3_test(
    name = "logger",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+loom@xmail.facebook.com"],
    deps = [
        ":utils",
        "//java/com/facebook/controllercallbacks:controllercallbacks",
        "//java/com/facebook/quicklog/module:quicklog",
        "//java/com/facebook/testing/powermock:powermock",
        "//java/com/facebook/testing/robolectric:robolectric",
        "//java/com/facebook/testing/robolectric/v3:v3",
        "//java/com/facebook/testing/robolectric/v3/shadows:shadows",
        loom_path("deps/jsr-305:jsr-305"),
        loom_path("java/main/com/facebook/loom/core:core"),
        loom_path("java/main/com/facebook/loom/core:events"),
        loom_path("java/main/com/facebook/loom/logger:logger"),
        "//third-party/java/assertj:assertj-android",
        "//third-party/java/assertj:assertj-core",
        "//third-party/java/fest:fest",
        "//third-party/java/fest:fest_android",
        "//third-party/java/guava:guava",
        "//third-party/java/junit:junit",
        "//third-party/java/mockito:mockito",
        "//third-party/java/robolectric3/robolectric:robolectric",
    ],
)
