# BUILD FILE SYNTAX: SKYLARK
load("//buck_imports:profilo_path.bzl", "profilo_path")

python_library(
    name = "runner-lib",
    srcs = glob(["*.py"]),
    base_module = "profilo",
    deps = [
        profilo_path("python/profilo/importer:importer"),
        profilo_path("python/profilo/model:model"),
    ],
)

# python_binary(
#     name = "runner",
#     main_module = "profilo",
#     platform = "py3any",
#     deps = [
#         ":runner-lib",
#     ],
# )
