load("//buck_imports:profilo_path.bzl", "profilo_path")
load("//tools/build_defs:robolectric3_test.bzl", "robolectric3_test")

robolectric3_test(
    name = "config",
    srcs = glob(
        [
            "coldstart/*Test.java",
            "*Test.java",
        ],
        exclude = [
            "json/**/*",
        ],
    ),
    contacts = ["oncall+loom@xmail.facebook.com"],
    deps = [
        "//java/com/facebook/quicklog:quicklog",
        "//java/com/facebook/testing/inject:inject",
        "//java/com/facebook/testing/powermock:powermock",
        "//java/com/facebook/testing/robolectric/v3:v3",
        "//java/com/facebook/testing/util:util",
        profilo_path("deps/jsr-305:jsr-305"),
        profilo_path("facebook/java/main/com/facebook/profilo/config/coldstart:coldstart"),
        profilo_path("facebook/java/main/com/facebook/profilo/config/json:json"),
        profilo_path("java/main/com/facebook/profilo/config:config"),
        profilo_path("java/main/com/facebook/profilo/core:core"),
        "//third-party/java/assertj:assertj-core",
        "//third-party/java/fest:fest",
        "//third-party/java/fest:fest_util",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson",
        "//third-party/java/junit:junit",
        "//third-party/java/robolectric3/robolectric:robolectric",
    ],
)
