// Copyright 2004-present Facebook. All Rights Reserved.
// Generated by: //native/museum/run_codegen.sh
// This is generated code -- do not modify manually.

// @generated SignedSource<<986cf538fd8a689bad1bc613533633b9>>
// @model md5 d924b588e6db1177d1c8c6d909ac19b7

#pragma once

namespace facebook { namespace museum { namespace MUSEUM_VERSION { namespace libart {

void preinitSymbols();
} } } } // namespace facebook::museum::MUSEUM_VERSION::libart
