# BUILD FILE SYNTAX: SKYLARK
load("//buck_imports:profilo_path.bzl", "profilo_path")
load("//build_defs:fb_xplat_cxx_library.bzl", "fb_xplat_cxx_library")

fb_xplat_cxx_library(
    name = "threadmetadata",
    srcs = [
        "ThreadMetadata.cpp",
        "jni.cpp",
    ],
    headers = glob(
        ["*.h"],
    ),
    header_namespace = "profilo/threadmetadata",
    allow_jni_merging = True,
    compiler_flags = [
        "-fvisibility=hidden",
        "-fexceptions",
        "-std=gnu++14",
    ],
    soname = "libprofilo_threadmetadata.$(ext)",
    visibility = [
        profilo_path("java/main/com/facebook/profilo/provider/threadmetadata:"),
    ],
    deps = [
        profilo_path("cpp:profilo"),
        profilo_path("cpp/logger:logger"),
        profilo_path("cpp/util:util"),
        profilo_path("deps/fb:fb"),
        profilo_path("deps/fbjni:fbjni"),
    ],
)
