# BUILD FILE SYNTAX: SKYLARK
load("//build_defs:fb_core_android_library.bzl", "fb_core_android_library")
load("//buck_imports:profilo_path.bzl", "profilo_path")

fb_core_android_library(
    name = "systemcounters",
    srcs = [
        "SystemCounterLogger.java",
        "SystemCounterThread.java",
    ],
    visibility = [profilo_path("...")],
    deps = [
        profilo_path("cpp/systemcounters:systemcounters"),
        profilo_path("deps/fbjni:fbjni-java"),
        profilo_path("deps/jsr-305:jsr-305"),
        profilo_path("deps/proguard:annotations"),
        profilo_path("deps/soloader:soloader"),
        profilo_path("java/main/com/facebook/profilo/core:core"),
        profilo_path("java/main/com/facebook/profilo/core:events"),
    ],
)
