load("//libraries/loom/buck_imports:deps", "loom_path")

android_library(
    name = "config",
    srcs = glob([
        "*.java",
    ]),
    tests = [
        loom_path("java/test/com/facebook/loom/config:config"),
    ],
    visibility = [
        "//instrumentation_tests/com/facebook/quicklog/...",
        loom_path("..."),
        "//perftests/benchmarks/java/com/facebook/benchmarks/loom/...",
    ],
    deps = [
        loom_path("deps/jsr-305:jsr-305"),
        loom_path("java/main/com/facebook/loom/core:constants"),
    ],
)
