load("//libraries/loom/buck_imports:deps", "loom_path")

android_library(
    name = "network",
    srcs = [
        "NetworkLigerProvider.java",
        "NetworkVideoProvider.java",
    ],
    visibility = [loom_path("...")],
    deps = [
        "//java/com/facebook/jni:jni",
        "//java/com/facebook/proguard/annotations:annotations",
        "//java/com/facebook/tigon/tigonapi:tigonapi",
        "//java/com/facebook/tigon/tigonliger:tigonliger",
        "//java/com/facebook/tigon/tigonvideo:tigonvideo",
        loom_path("facebook/cpp/network:network"),
        loom_path("java/main/com/facebook/loom/core:core"),
        loom_path("java/main/com/facebook/loom/core:events"),
        "//libraries/soloader/java/com/facebook/soloader:soloader",
    ],
)
