load("//tools/build_defs:fb_python_test.bzl", "fb_python_test")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

fb_python_test(
    name = "tests",
    srcs = glob(["*.py"]),
    base_module = "profilo.model.tests",
    deps = [
        profilo_path("python/profilo/model:model"),
    ],
)
