# BUILD FILE SYNTAX: SKYLARK
load("//build_defs:fb_core_android_library.bzl", "fb_core_android_library")
load("//buck_imports:profilo_path.bzl", "profilo_path")

fb_core_android_library(
    name = "aidl",
    srcs = glob(["java/**/*.java"]) + [
        ":IProfiloMultiProcessTraceService",
        ":IProfiloMultiProcessTraceListener",
    ],
    visibility = [
        profilo_path("..."),
    ],
)

gen_aidl(
    name = "IProfiloMultiProcessTraceService",
    aidl = "java/com/facebook/profilo/ipc/IProfiloMultiProcessTraceService.aidl",
    import_path = profilo_path("aidl/java/").replace("//", ""),
)

gen_aidl(
    name = "IProfiloMultiProcessTraceListener",
    aidl = "java/com/facebook/profilo/ipc/IProfiloMultiProcessTraceListener.aidl",
    import_path = profilo_path("aidl/java/").replace("//", ""),
)
