load("//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load("//tools/build_defs/android:fb_core_android_library.bzl", "fb_core_android_library")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_import_path", "profilo_path")

fb_core_android_library(
    name = "aidl",
    srcs = glob(["java/**/*.java"]) + [
        ":IProfiloMultiProcessTraceService",
        ":IProfiloMultiProcessTraceListener",
    ],
    labels = ["supermodule:android/default/loom.core"],
    visibility = [
        profilo_path("..."),
    ],
    deps = [
        profilo_path("java/main/com/facebook/profilo/config:config"),
        profilo_path("java/main/com/facebook/profilo/logger:logger"),
        profilo_path("deps/jsr-305:jsr-305"),
    ],
    exported_deps = [
        profilo_path("java/main/com/facebook/profilo/mmapbuf:mmapbuf"),
    ],
)

fb_native.gen_aidl(
    name = "IProfiloMultiProcessTraceService",
    aidl = "java/com/facebook/profilo/ipc/IProfiloMultiProcessTraceService.aidl",
    import_path = profilo_import_path("aidl/java/"),
)

fb_native.gen_aidl(
    name = "IProfiloMultiProcessTraceListener",
    aidl = "java/com/facebook/profilo/ipc/IProfiloMultiProcessTraceListener.aidl",
    import_path = profilo_import_path("aidl/java/"),
)
