load("//tools/build_defs/android:fb_core_android_library.bzl", "fb_core_android_library")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

fb_core_android_library(
    name = "config",
    srcs = glob([
        "*.java",
    ]),
    labels = [],
    visibility = [
        "//fbandroid/instrumentation_tests/com/facebook/quicklog/...",
        profilo_path("..."),
        "//fbandroid/instrumentation_tests/com/facebook/profilo/...",
        "//fbandroid/perftests/benchmarks/java/com/facebook/benchmarks/profilo/...",
    ],
    deps = [
        profilo_path("deps/jsr-305:jsr-305"),
        profilo_path("deps/proguard:annotations"),
        profilo_path("java/main/com/facebook/profilo/core:constants"),
        profilo_path("java/main/com/facebook/profilo/core:registry"),
    ],
)
