load("//buck_imports:profilo_path.bzl", "profilo_path")

android_library(
    name = "config",
    srcs = glob([
        "*.java",
    ]),
    tests = [
        profilo_path("java/test/com/facebook/profilo/config:config"),
    ],
    visibility = [
        "//instrumentation_tests/com/facebook/quicklog/...",
        profilo_path("..."),
        "//perftests/benchmarks/java/com/facebook/benchmarks/loom/...",
    ],
    deps = [
        profilo_path("deps/jsr-305:jsr-305"),
        profilo_path("java/main/com/facebook/profilo/core:constants"),
    ],
)
