load("//libraries/loom/buck_imports:deps", "loom_path")

python_library(
    name = "importer",
    srcs = glob(["*.py"]),
    base_module = "loom.importer",
    visibility = [
        loom_path("python/..."),
    ],
    deps = [
        loom_path("python/loom/model:model"),
    ],
)
