android_library(
    name = "api",
    srcs = glob(["*.java"]),
    proguard_config = "proguard.pro",
    provided_deps = [
        loom_path("deps/jsr-305:jsr-305"),
        loom_path("java/main/com/facebook/loom/core:control"),
        loom_path("java/main/com/facebook/loom/core:events"),
    ],
    visibility = ["PUBLIC"],
)
