load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_cxx_binary", "profilo_cxx_test", "profilo_path")

profilo_cxx_binary(
    name = "procfs_perf",
    srcs = [
        "procfs_perf.cpp",
    ],
    compiler_flags = [
        "-fexceptions",
        "-frtti",
        "-DLOG_TAG=\"Profilo\"",
        "-g3",
        "-fPIE",
    ],
    linker_flags = [
        "-pie",
    ],
    deps = [
        profilo_path("cpp/counters:counters"),
    ],
)

profilo_cxx_test(
    name = "procfs",
    srcs = [
        "ProcFsTest.cpp",
    ],
    compiler_flags = [
        "-fexceptions",
        "-frtti",
        "-std=gnu++14",
        "-DLOG_TAG=\"Profilo\"",
    ],
    labels = ["opt-in-sandcastle-sanitized-test"],
    linker_flags = [
        "-ldl",
    ],
    deps = [
        "//xplat/folly:experimental_test_util",
        profilo_path("cpp/counters:counters"),
        profilo_path("cpp/logger:logger_static"),
    ],
)

profilo_cxx_test(
    name = "counter",
    srcs = [
        "CounterTest.cpp",
    ],
    compiler_flags = [
        "-fexceptions",
        "-frtti",
        "-std=gnu++14",
        "-DLOG_TAG=\"Profilo\"",
    ],
    labels = ["opt-in-sandcastle-sanitized-test"],
    linker_flags = [
        "-ldl",
    ],
    deps = [
        "//xplat/folly:experimental_test_util",
        "//xplat/third-party/gmock:gmock",
        profilo_path("cpp/counters:counters"),
    ],
)
