// Copyright 2004-present Facebook. All Rights Reserved.
// Generated by: //native/museum/run_codegen.sh
// This is generated code -- do not modify manually.

// @generated SignedSource<<85ad91e3eaaa8355facee656312c8988>>
// @model md5 d29b1a403a21e2f8ff5302de9232d7fd

#pragma once

namespace facebook { namespace museum { namespace MUSEUM_VERSION { namespace libart {

void preinitSymbols();
} } } } // namespace facebook::museum::MUSEUM_VERSION::libart
