# BUILD FILE SYNTAX: SKYLARK
load("//buck_imports:profilo_path.bzl", "profilo_path")

cxx_binary(
    name = "procfs_perf",
    srcs = [
        "procfs_perf.cpp",
    ],
    compiler_flags = [
        "-fexceptions",
        "-DLOG_TAG=\"Profilo\"",
        "-g3",
        "-fPIE",
    ],
    linker_flags = [
        "-pie",
    ],
    deps = [
        profilo_path("cpp/util:util"),
    ],
)

cxx_test(
    name = "procfs",
    srcs = [
        "ProcFsTest.cpp",
    ],
    compiler_flags = [
        "-fexceptions",
        "-std=gnu++14",
        "-DLOG_TAG=\"Profilo\"",
    ],
    linker_flags = [
        "-pthread",
        "-ldl",
    ],
    deps = [
        "xplat//folly:test-util",
        profilo_path("cpp/util:util"),
    ],
)
