load("//buck_imports:profilo_path.bzl", "profilo_path")

python_test(
    name = "tests",
    srcs = glob(["*.py"]),
    base_module = "loom.model.tests",
    deps = [
        profilo_path("python/loom/model:model"),
    ],
)
