load("//tools/build_defs/android:fb_core_android_library.bzl", "fb_core_android_library")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

fb_core_android_library(
    name = "api",
    srcs = glob(["*.java"]),
    labels = [],
    provided_deps = [
        profilo_path("java/main/com/facebook/profilo/provider/stacktrace:stacktrace"),
    ],
    visibility = [
        "PUBLIC",
    ],
)
