load("//libraries/loom/buck_imports:deps", "loom_path")

android_library(
    name = "transientdata",
    srcs = [
        "TransientNetworkDataProvider.java",
    ],
    tests = [
        loom_path("facebook/java/test/com/facebook/loom/provider/transientdata:transientdata"),
    ],
    visibility = [
        "//java/com/facebook/cloudseeder:cloudseeder",
        "//javatests/com/facebook/cloudseeder:cloudseeder",
        loom_path("..."),
    ],
    deps = [
        "//java/com/facebook/cloudseeder/tracedata:tracedata",
        loom_path("java/main/com/facebook/loom/core:core"),
        loom_path("java/main/com/facebook/loom/core:events"),
        "//third-party/java/jsr-305:jsr-305",
    ],
)
