load("@fbsource//tools/build_defs/android:robolectric4_test.bzl", "robolectric4_test")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

robolectric4_test(
    name = "core",
    srcs = glob(["*Test.java"]),
    contacts = ["oncall+loom@xmail.facebook.com"],
    use_binary_resources = True,
    deps = [
        "//fbandroid/java/com/facebook/testing/inject:inject",
        "//fbandroid/java/com/facebook/testing/util:util",
        profilo_path("deps/fbtrace:utils"),
        profilo_path("deps/jsr-305:jsr-305"),
        profilo_path("deps/soloader:soloader"),
        profilo_path("java/main/com/facebook/profilo/core:core"),
        profilo_path("java/main/com/facebook/profilo/writer:writer"),
        profilo_path("java/test/com/facebook/profilo/logger:utils"),
        profilo_path("java/test/com/facebook/profilo/util:util"),
        "//fbandroid/third-party/java/assertj:assertj-android",
        "//fbandroid/third-party/java/assertj:assertj-core",
        "//fbandroid/third-party/java/fest:fest",
        "//fbandroid/third-party/java/fest:fest_android",
        "//fbandroid/third-party/java/guava:guava",
        "//fbandroid/third-party/java/junit:junit",
    ],
)
