load("//tools/build_defs/android:fb_core_android_library.bzl", "fb_core_android_library")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

fb_core_android_library(
    name = "provider",
    visibility = [
        "//java/com/facebook/cloudseeder:cloudseeder",
        "//javatests/com/facebook/cloudseeder:cloudseeder",
        profilo_path("..."),
        "//perftests/benchmarks/java/com/facebook/benchmarks/profilo/...",
    ],
    deps = [
        profilo_path("java/main/com/facebook/profilo/provider/stacktrace:stacktrace"),
        profilo_path("java/main/com/facebook/profilo/provider/systemcounters:systemcounters"),
    ],
)
