load("//buck_imports:loom_path.bzl", "loom_path")

android_library(
    name = "provider",
    visibility = [
        "//instrumentation_tests/com/facebook/loom/...",
        "//java/com/facebook/cloudseeder:cloudseeder",
        "//javatests/com/facebook/cloudseeder:cloudseeder",
        loom_path("..."),
        "//perftests/benchmarks/java/com/facebook/benchmarks/loom/...",
    ],
    deps = [
        loom_path("java/main/com/facebook/loom/provider/stacktrace:stacktrace"),
        loom_path("java/main/com/facebook/loom/provider/systemcounters:systemcounters"),
    ],
)
