load("//libraries/loom/buck_imports:deps", "loom_path")

android_library(
    name = "provider",
    srcs = ["TigonServiceProvider.java"],
    visibility = [
        "//java/com/facebook/video/vps/tigonnetworkstackadapter:tigonnetworkstackadapter",
        loom_path("..."),
    ],
    deps = [
        "//java/com/facebook/tigon/iface:iface",
        "//java/com/facebook/tigon/tigonapi:tigonapi",
        "//java/com/facebook/tigon/tigonvideo:tigonvideo",
    ],
)

android_library(
    name = "vps",
    srcs = ["LoomTigonInitializer.java"],
    exported_deps = [
        ":provider",
        "//java/com/facebook/tigon/iface:iface",
        "//java/com/facebook/tigon/tigonapi:tigonapi",
        "//java/com/facebook/tigon/tigonvideo:tigonvideo",
    ],
    visibility = [
        "//java/com/facebook/katana/app:app",
    ],
    deps = [
        "xplat//proxygen:ligerAndroid",
        ":provider",
        "//java/com/facebook/cloudseeder/iface:iface",
        "//java/com/facebook/cloudseeder/tracedata:tracedata",
        "//java/com/facebook/common/appstate:appstate",
        "//java/com/facebook/common/process:process",
        "//java/com/facebook/common/time:time",
        "//java/com/facebook/http/executors/liger:liger",
        "//java/com/facebook/proguard/annotations:annotations",
        "//java/com/facebook/quicklog/module:quicklog",
        "//java/com/facebook/tigon/iface:iface",
        "//java/com/facebook/tigon/tigonapi:tigonapi",
        "//java/com/facebook/tigon/tigonvideo:tigonvideo",
        loom_path("facebook/java/main/com/facebook/loom/provider/network:network"),
        loom_path("facebook/java/main/com/facebook/loom/provider/transientdata:transientdata"),
        loom_path("java/main/com/facebook/loom/core:core"),
        loom_path("java/main/com/facebook/loom/core:events"),
        "//third-party/java/jsr-305:jsr-305",
    ],
)
