load("//tools/build_defs:fb_python_library.bzl", "fb_python_library")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

fb_python_library(
    name = "model",
    srcs = glob(["*.py"]),
    base_module = "profilo.model",
    visibility = [
        profilo_path("python/..."),
    ],
)
