load("//buck_imports:profilo_path.bzl", "profilo_path")

android_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = [
        profilo_path("..."),
    ],
    deps = [
        "//java/com/facebook/testing/powermock:powermock",
        profilo_path("java/main/com/facebook/profilo/core:core"),
        "//third-party/java/junit:junit",
    ],
)
