load("//tools/build_defs/android:fb_core_android_library.bzl", "fb_core_android_library")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

fb_core_android_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//java/com/facebook/testing/powermock:powermock",
        profilo_path("java/main/com/facebook/profilo/core:core"),
        "//third-party/java/junit:junit",
    ],
)
