load("//tools/build_defs/android:fb_xplat_android_cxx_library.bzl", "fb_xplat_android_cxx_library")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

SYSTEM_COUNTERS_EXPORTED_HEADERS = [
    "ProcessCounters.h",
    "SystemCounterThread.h",
    "ThreadCounters.h",
]

fb_xplat_android_cxx_library(
    name = "systemcounters",
    srcs = glob(["*.cpp"]),
    headers = glob(
        ["*.h"],
        exclude = SYSTEM_COUNTERS_EXPORTED_HEADERS,
    ),
    header_namespace = "profilo/systemcounters",
    exported_headers = SYSTEM_COUNTERS_EXPORTED_HEADERS,
    allow_jni_merging = True,
    compiler_flags = [
        "-fexceptions",
        "-frtti",
        "-std=gnu++14",
    ],
    labels = [],
    soname = "libprofilo_systemcounters.$(ext)",
    visibility = [
        profilo_path("cpp/test/systemcounters/..."),
        profilo_path("java/main/com/facebook/profilo/provider/systemcounters:"),
        profilo_path("facebook/cpp/disk/..."),
        profilo_path("facebook/java/test/com/facebook/profilo/instrumentation_tests/..."),
    ],
    deps = [
        profilo_path("cpp:profilo"),
        profilo_path("cpp/counters:counters"),
        profilo_path("cpp/jni:jmulti_buffer_logger"),
        profilo_path("cpp/logger:multi_buffer_logger"),
        profilo_path("cpp/logger/buffer:buffer"),
        profilo_path("cpp/util:util"),
        profilo_path("deps/fb:fb"),
        profilo_path("deps/fbjni:fbjni"),
        profilo_path("deps/procmaps:procmaps"),
    ],
)
