load("//buck_imports:loom_path.bzl", "loom_path")

android_library(
    name = "init",
    srcs = [
        "ClassStatsPeriodicRunnable.java",
        "LoomColdStartTraceInitializer.java",
    ],
    tests = [],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//java/com/facebook/annotations:annotations",
        "//java/com/facebook/base/lwperf/perfstats:perfstats",
        "//java/com/facebook/common/dextricks/stats:stats",
        "//java/com/facebook/quicklog/identifiers:identifiers",
        loom_path("facebook/java/main/com/facebook/loom/config/coldstart:coldstart"),
        loom_path("facebook/java/main/com/facebook/loom/controllers:controllers"),
        loom_path("facebook/java/main/com/facebook/loom/core/api:api"),
        loom_path("facebook/java/main/com/facebook/loom/logger/api:api"),
        loom_path("facebook/java/main/com/facebook/loom/logger:logger"),  # T23692815
        loom_path("java/main/com/facebook/loom/config:config"),
        loom_path("java/main/com/facebook/loom/controllers/manual:manual"),
        loom_path("java/main/com/facebook/loom/core:core"),
        loom_path("java/main/com/facebook/loom/provider/atrace:atrace"),
        loom_path("facebook/java/main/com/facebook/loom/provider/libcio:libcio"),
        loom_path("facebook/java/main/com/facebook/loom/provider/fbsystrace:fbsystrace"),
        loom_path("java/main/com/facebook/loom/provider/stacktrace:stacktrace"),
        loom_path("java/main/com/facebook/loom/provider/systemcounters:systemcounters"),
        loom_path("java/main/com/facebook/loom/provider/threadmetadata:threadmetadata"),
        loom_path("java/main/com/facebook/loom/provider/yarn:yarn"),
        "//third-party/java/jsr-305:jsr-305",
        "//third-party/java/jsr-330:jsr-330",
    ],
)

android_library(
    name = "instagram",
    srcs = [
        "LoomIgInitializer.java",
    ],
    tests = [],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        loom_path("facebook/java/main/com/facebook/loom/core/api:api"),
        loom_path("facebook/java/main/com/facebook/loom/logger/api:api"),
        loom_path("java/main/com/facebook/loom/controllers/external:external"),
        loom_path("java/main/com/facebook/loom/config:config"),
        loom_path("java/main/com/facebook/loom/core:core"),
        loom_path("java/main/com/facebook/loom/provider/atrace:atrace"),
        loom_path("facebook/java/main/com/facebook/loom/provider/libcio:libcio"),
        loom_path("java/main/com/facebook/loom/provider/stacktrace:stacktrace"),
        loom_path("java/main/com/facebook/loom/provider/systemcounters:systemcounters"),
        loom_path("java/main/com/facebook/loom/provider/threadmetadata:threadmetadata"),
        "//third-party/java/jsr-305:jsr-305",
        "//third-party/java/jsr-330:jsr-330",
    ],
)

android_library(
    name = "fblite_init",
    srcs = [
        "LiteBackgroundUploadService.java",
        "LiteLoomInitializer.java",
    ],
    tests = [],
    visibility = [
        "//apps/fblite/xMob-android/...",
        "//java/com/facebook/lite/loom/...",
    ],
    deps = [
        "//apps/fblite/common.xMob:common",
        "//java/com/facebook/common/mobilelab:mobilelab",
        loom_path("facebook/java/main/com/facebook/loom/core/api:api"),
        loom_path("facebook/java/main/com/facebook/loom/logger/api:api"),
        loom_path("java/main/com/facebook/loom/config:config"),
        loom_path("java/main/com/facebook/loom/controllers/manual:manual"),
        loom_path("java/main/com/facebook/loom/core:core"),
        loom_path("java/main/com/facebook/loom/provider/stacktrace:stacktrace"),
        "//third-party/java/jsr-305:jsr-305",
        "//third-party/java/yearclass:yearclass",
    ],
)
