load("//libraries/loom/buck_imports:deps", "loom_path")

android_library(
    name = "atrace",
    srcs = glob(["*.java"]),
    visibility = [
        "//javatests/com/facebook/loom/...",
        loom_path("..."),
    ],
    deps = [
        loom_path("cpp/atrace:atrace"),
        loom_path("deps/proguard:annotations"),
        loom_path("deps/soloader:soloader"),
        loom_path("java/main/com/facebook/loom/core:core"),
    ],
)
