load("//libraries/loom/buck_imports:deps", "loom_path")

android_library(
    name = "fbsystrace",
    srcs = glob(["*.java"]),
    visibility = [
        loom_path("..."),
    ],
    deps = [
        "//java/com/facebook/systrace:systrace",
        loom_path("java/main/com/facebook/loom/core:core"),
    ],
)
