load("//libraries/loom/buck_imports:deps", "loom_path")

android_library(
    name = "controllers",
    srcs = glob(["*.java"]),
    tests = [
        loom_path("facebook/java/test/com/facebook/loom/controllers:controllers"),
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//java/com/facebook/common/json:json",
        "//java/com/facebook/quicklog:quicklog",
        "//java/com/facebook/quicklog/identifiers:identifiers",
        "//java/com/facebook/sequencelogger:interface",
        loom_path("facebook/java/main/com/facebook/loom/config/coldstart:coldstart"),
        loom_path("facebook/java/main/com/facebook/loom/config/json:json"),
        loom_path("java/main/com/facebook/loom/config:config"),
        loom_path("java/main/com/facebook/loom/core:constants"),
        loom_path("java/main/com/facebook/loom/core:control"),
        "//third-party/java/jsr-305:jsr-305",
        "//third-party/java/jsr-330:jsr-330",
    ],
)
