# BUILD FILE SYNTAX: SKYLARK
load("//build_defs:fb_core_android_library.bzl", "fb_core_android_library")
load("//buck_imports:profilo_path.bzl", "profilo_path")

fb_core_android_library(
    name = "stacktrace",
    srcs = glob(["*.java"]),
    visibility = [profilo_path("...")],
    deps = [
        profilo_path("cpp/profiler:profiler"),
        profilo_path("deps/jsr-305:jsr-305"),
        profilo_path("deps/proguard:annotations"),
        profilo_path("deps/soloader:soloader"),
        profilo_path("java/main/com/facebook/profilo/core:core"),
        profilo_path("java/main/com/facebook/profilo/core:events"),
        profilo_path("java/main/com/facebook/profilo/experiments:experiments"),
        profilo_path("java/main/com/facebook/profilo/logger:logger"),
    ],
)
