load("//tools/build_defs:fb_python_library.bzl", "fb_python_library")
load("//tools/build_defs/oss:profilo_defs.bzl", "profilo_path")

fb_python_library(
    name = "importer",
    srcs = glob(["*.py"]),
    base_module = "profilo.importer",
    visibility = [
        profilo_path("python/..."),
    ],
    deps = [
        profilo_path("python/profilo/model:model"),
    ],
)
