load("//tools/build_defs:fb_native_wrapper.bzl", "fb_native")

fb_native.python_library(
    name = "codegen-lib",
    srcs = glob(["**/*.py"]),
    base_module = "profilo.codegen",
)

fb_native.python_binary(
    name = "codegen",
    main_module = "profilo.codegen",
    deps = [
        ":codegen-lib",
    ],
)
