# BUILD FILE SYNTAX: SKYLARK
python_library(
    name = "codegen-lib",
    srcs = glob(["**/*.py"]),
    base_module = "profilo.codegen",
)

python_binary(
    name = "codegen",
    main_module = "profilo.codegen",
    deps = [
        ":codegen-lib",
    ],
)
