load("//libraries/loom/buck_imports:deps", "loom_path")
load("//buck_imports:xplat", "fb_xplat_cxx_library")

NETWORK_EXPORTED_HEADERS = ["NetworkProvider.h"]

fb_xplat_cxx_library(
    name = "network",
    srcs = [
        "NetworkLigerProvider.cpp",
        "NetworkProvider.cpp",
        "NetworkVideoProvider.cpp",
        "jni.cpp",
    ],
    headers = glob(
        ["*.h"],
        excludes = NETWORK_EXPORTED_HEADERS,
    ),
    header_namespace = "loom/network",
    exported_headers = NETWORK_EXPORTED_HEADERS,
    allow_jni_merging = True,
    compiler_flags = [
        "-fvisibility=hidden",
        "-fexceptions",
        "-frtti",
        "-DLOG_TAG=\"Loom/Network\"",
    ],
    soname = "libloom_network.$(ext)",
    visibility = [
        loom_path("facebook/java/main/com/facebook/loom/provider/network:network"),
    ],
    deps = [
        "xplat//AsyncExecutor:AsyncExecutor",
        "xplat//AsyncExecutor:Observer",
        "xplat//Tigon:TigonSecretary",
        "xplat//TigonLiger:TigonLiger",
        "xplat//proxygen:liger",
        "//java/com/facebook/common/jniexecutors/jni:jniexecutors-jni",
        loom_path("cpp:loom"),
        loom_path("cpp/logger:logger"),
        loom_path("cpp/util:util"),
        "//native/fb:fb",
        "//native/tigonliger:tigonliger",
        "//native/tigonliger:tigonvideo",
    ],
)
