load("//build_defs:fb_core_android_library.bzl", "fb_core_android_library")
load("//buck_imports:profilo_path.bzl", "profilo_path")
load(
    profilo_path("build_defs:profilo_sample_app.bzl"),
    "profilo_sample_app",
)

keystore(
    name = "keystore",
    properties = "sample.keystore.properties",
    store = "sample.keystore",
    visibility = [
        profilo_path("..."),
    ],
)

android_manifest(
    name = "manifest",
    skeleton = "AndroidManifest.xml",
    visibility = [
        profilo_path("..."),
    ],
)

SAMPLE_LIB_SRCS = [
    "BaseSampleAppMainActivity.java",
    "WorkloadThread.java",
]

android_build_config(
    name = "sample-buildconfig-dummy",
    package = "com.facebook.profilo",
    values = [
        "String[] PROVIDERS = new String[] { }",
    ],
)

fb_core_android_library(
    name = "sample-lib",
    srcs = SAMPLE_LIB_SRCS,
    provided_deps = [
        ":sample-buildconfig-dummy",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        profilo_path("java/main/com/facebook/profilo/config:config"),
        profilo_path("java/main/com/facebook/profilo/controllers/external:external"),
        profilo_path("java/main/com/facebook/profilo/controllers/external/api:api"),
        profilo_path("java/main/com/facebook/profilo/core:core"),
        profilo_path("deps/soloader:soloader"),
    ],
)

ACTIVITY_SRCS = glob(
    ["*.java"],
    exclude = SAMPLE_LIB_SRCS,
)

profilo_sample_app(
    srcs = ACTIVITY_SRCS,
    manifest = "AndroidManifest.xml",
    providers = None,
)

# Referred to by open source buckconfig, don't forget to update it there.
profilo_sample_app(
    srcs = ACTIVITY_SRCS,
    manifest = "AndroidManifest.xml",
    providers = [
        "atrace",
        "stacktrace",
        "systemcounters",
        "threadmetadata",
    ],
)

profilo_sample_app(
    srcs = ACTIVITY_SRCS,
    manifest = "AndroidManifest.xml",
    providers = [
        "atrace",
        "processmetadata",
        "stacktrace",
        "systemcounters",
        "threadmetadata",
    ],
)

# Generate a target for each individual provider
for provider in [
        "atrace",
        "processmetadata",
        "stacktrace",
        "systemcounters",
        "threadmetadata",
        "yarn",
    ]:
    profilo_sample_app(
        srcs = ACTIVITY_SRCS,
        manifest = "AndroidManifest.xml",
        providers = [
            provider,
        ],
    )
