load("//buck_imports:loom_path.bzl", "loom_path")
load("//buck_imports:robolectric3_test", "robolectric3_test")

robolectric3_test(
    name = "config",
    srcs = glob(
        [
            "coldstart/*Test.java",
            "*Test.java",
        ],
        excludes = [
            "json/**/*",
        ],
    ),
    contacts = ["oncall+loom@xmail.facebook.com"],
    deps = [
        "//java/com/facebook/quicklog:quicklog",
        "//java/com/facebook/testing/inject:inject",
        "//java/com/facebook/testing/powermock:powermock",
        "//java/com/facebook/testing/robolectric/v3:v3",
        "//java/com/facebook/testing/util:util",
        loom_path("deps/jsr-305:jsr-305"),
        loom_path("facebook/java/main/com/facebook/loom/config/coldstart:coldstart"),
        loom_path("facebook/java/main/com/facebook/loom/config/json:json"),
        loom_path("java/main/com/facebook/loom/config:config"),
        loom_path("java/main/com/facebook/loom/core:core"),
        "//third-party/java/assertj:assertj-core",
        "//third-party/java/fest:fest",
        "//third-party/java/fest:fest_util",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson",
        "//third-party/java/junit:junit",
        "//third-party/java/robolectric3/robolectric:robolectric",
    ],
)
