load("//buck_imports:loom_path.bzl", "loom_path")

python_library(
    name = "model",
    srcs = glob(["*.py"]),
    base_module = "loom.model",
    visibility = [
        loom_path("python/..."),
    ],
)
