load("//libraries/loom/buck_imports:deps", "loom_path")
load("//buck_imports:robolectric3_test", "robolectric3_test")

robolectric3_test(
    name = "json",
    srcs = glob(["*Test.java"]),
    # Please change the contact to the oncall of your team
    contacts = ["delyank@fb.com"],
    deps = [
        "//java/com/facebook/common/json:json",
        "//java/com/facebook/inject:inject",
        "//java/com/facebook/testing/automock:automock",
        "//java/com/facebook/testing/inject:inject",
        "//java/com/facebook/testing/robolectric/v3:v3",
        loom_path("facebook/java/main/com/facebook/loom/config/json:json"),
        loom_path("java/main/com/facebook/loom/config:config"),
        loom_path("java/main/com/facebook/loom/core:core"),
        "//third-party/java/assertj:assertj-core",
        "//third-party/java/fest:fest",
        "//third-party/java/guava:guava",
        "//third-party/java/jackson:jackson",
        "//third-party/java/jsr-305:jsr-305",
        "//third-party/java/jsr-330:jsr-330",
        "//third-party/java/junit:junit",
        "//third-party/java/mockito:mockito",
        "//third-party/java/robolectric3/robolectric:robolectric",
    ],
)
