load("//buck_imports:profilo_path.bzl", "profilo_path")

python_library(
    name = "runner-lib",
    srcs = glob(["*.py"]),
    base_module = "loom",
    deps = [
        profilo_path("python/loom/importer:importer"),
        profilo_path("python/loom/model:model"),
    ],
)

# python_binary(
#     name = "runner",
#     main_module = "loom",
#     platform = "py3any",
#     deps = [
#         ":runner-lib",
#     ],
# )
