// Copyright 2004-present Facebook. All Rights Reserved.
// Generated by: //native/museum/run_codegen.sh
// This is generated code -- do not modify manually.

// @generated SignedSource<<a39ddd04092d12ee997fe19a2af4d5cc>>
// @model md5 73a6a31279d7f323cb1ba6ab3afc66c6

#pragma once

namespace facebook { namespace museum { namespace MUSEUM_VERSION { namespace libart {

void preinitSymbols();
} } } } // namespace facebook::museum::MUSEUM_VERSION::libart
